import type { RecipeSeed } from "./recipes";

/**
 * Recetas para la alimentación complementaria (desde los 6 meses).
 * Reglas comunes: sin sal, sin azúcar, sin miel antes del año, texturas
 * adaptadas a la edad y alimentos seguros para evitar atragantamientos.
 * Las porciones son orientativas: el bebé regula cuánto come.
 */

const BASE = { audience: "baby" as const, difficulty: "fácil" as const };

export const BABY_RECIPES: RecipeSeed[] = [
  /* ------------------------- 6 meses: primeros sabores ------------------------- */
  {
    ...BASE,
    slug: "bebe-pure-calabaza",
    name: "Puré de calabaza",
    emoji: "🎃",
    description: "Uno de los primeros purés: dulce, suave y fácil de digerir.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["primeros sabores", "freezer"],
    servings: 4,
    prep: 5,
    cook: 20,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [
      ["zapallo", 300],
      ["aceite-oliva", 5, "en crudo, al servir"],
    ],
    steps: [
      "Pelá la calabaza, sacale las semillas y cortala en cubos.",
      "Cociná al vapor o hervida en poca agua 15-20 minutos, hasta que esté muy tierna.",
      "Procesá o pisá con tenedor agregando un poco del agua de cocción hasta lograr un puré liso.",
      "Al servir, agregá unas gotas de aceite de oliva crudo. Sin sal.",
      "Ofrecé de a cucharaditas y respetá cuando cierre la boca o gire la cabeza.",
    ],
    storage: "48 h en heladera o 1 mes en freezer en cubeteras.",
  },
  {
    ...BASE,
    slug: "bebe-pure-zapallo-zanahoria",
    name: "Puré de calabaza y zanahoria",
    emoji: "🥕",
    description: "Combinación clásica, rica en vitamina A.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["primeros sabores", "freezer"],
    servings: 4,
    prep: 5,
    cook: 20,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [
      ["zapallo", 200],
      ["zanahoria", 120],
      ["aceite-oliva", 5],
    ],
    steps: [
      "Pelá y cortá la calabaza y la zanahoria en cubos chicos.",
      "Cociná al vapor 20 minutos (la zanahoria tarda un poco más: cortala más chica).",
      "Procesá con un poco de agua de cocción hasta que quede liso.",
      "Agregá el aceite crudo al servir.",
    ],
    storage: "48 h en heladera o 1 mes en freezer.",
  },
  {
    ...BASE,
    slug: "bebe-pure-papa-zapallo-pollo",
    name: "Puré de papa, calabaza y pollo",
    emoji: "🍗",
    description: "Primera comida completa: verdura + hidrato + proteína con hierro.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["hierro", "comida completa", "freezer"],
    servings: 3,
    prep: 10,
    cook: 25,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [
      ["papa", 100],
      ["zapallo", 100],
      ["pechuga-pollo", 45],
      ["aceite-oliva", 5],
    ],
    steps: [
      "Cociná el pollo en agua sin sal 15 minutos, hasta que esté bien cocido (sin partes rosadas).",
      "En la misma agua cociná la papa y la calabaza en cubos 15 minutos.",
      "Procesá el pollo con un poco del caldo hasta que quede bien fino; luego sumá las verduras.",
      "Ajustá la textura con caldo y agregá el aceite al servir.",
    ],
    tips: "La carne es la principal fuente de hierro a esta edad: ofrecela todos los días.",
    storage: "24 h en heladera o 1 mes en freezer.",
  },
  {
    ...BASE,
    slug: "bebe-pure-carne-zapallito",
    name: "Puré de carne, zapallito y papa",
    emoji: "🥩",
    description: "Rico en hierro y zinc, clave desde los 6 meses.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["hierro", "comida completa", "freezer"],
    servings: 3,
    prep: 10,
    cook: 20,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [
      ["carne-picada-magra", 45],
      ["zapallito", 100],
      ["papa", 80],
      ["aceite-oliva", 5],
    ],
    steps: [
      "Cociná la carne picada en una ollita con un poco de agua, desgranándola, hasta que esté bien cocida.",
      "Agregá la papa y el zapallito en cubos, cubrí con agua y cociná 15 minutos.",
      "Procesá todo junto hasta lograr la textura deseada.",
      "Agregá el aceite crudo al servir. Sin sal.",
    ],
    storage: "24 h en heladera o 1 mes en freezer.",
  },
  {
    ...BASE,
    slug: "bebe-manzana-cocida",
    name: "Compota de manzana",
    emoji: "🍎",
    description: "Postre suave para las primeras semanas.",
    mealTypes: ["merienda", "desayuno"],
    tags: ["fruta", "primeros sabores", "freezer"],
    servings: 3,
    prep: 5,
    cook: 12,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [
      ["manzana", 180],
      ["canela", 0.2, "opcional, una pizca"],
    ],
    steps: [
      "Pelá la manzana, quitale el centro y cortala en cubos.",
      "Cociná con 3 cucharadas de agua, tapado, 10-12 minutos.",
      "Pisá o procesá. Sin azúcar.",
    ],
    storage: "48 h en heladera.",
  },
  {
    ...BASE,
    slug: "bebe-pera-pisada",
    name: "Pera pisada",
    emoji: "🍐",
    description: "Fruta suave, ayuda al tránsito intestinal.",
    mealTypes: ["merienda", "desayuno"],
    tags: ["fruta", "primeros sabores", "sin cocción"],
    servings: 2,
    prep: 5,
    cook: 0,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [["pera", 180, "bien madura"]],
    steps: [
      "Elegí una pera bien madura y blanda.",
      "Pelala, sacale el centro y pisala con tenedor hasta que quede suave.",
      "Si está dura, cocinala 5 minutos al vapor antes de pisar.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-banana-pisada",
    name: "Banana pisada",
    emoji: "🍌",
    description: "La más práctica: sin cocción y siempre a mano.",
    mealTypes: ["merienda", "desayuno"],
    tags: ["fruta", "primeros sabores", "sin cocción"],
    servings: 2,
    prep: 2,
    cook: 0,
    babyMinMonths: 6,
    babyTexture: "puré liso / BLW",
    ingredients: [["banana", 100, "madura"]],
    steps: [
      "Pisá la banana con tenedor hasta que quede cremosa.",
      "Para BLW: cortá la banana en 3 trozos a lo largo y ofrecé un bastón (se agarra mejor con un poco de cáscara en la base).",
    ],
  },
  {
    ...BASE,
    slug: "bebe-palta-pisada",
    name: "Palta pisada",
    emoji: "🥑",
    description: "Grasas saludables para el desarrollo cerebral.",
    mealTypes: ["almuerzo", "merienda", "cena"],
    tags: ["primeros sabores", "sin cocción"],
    servings: 2,
    prep: 3,
    cook: 0,
    babyMinMonths: 6,
    babyTexture: "puré liso / BLW",
    ingredients: [["palta", 80, "madura"]],
    steps: [
      "Elegí una palta bien madura (que ceda al presionarla).",
      "Pisala con tenedor hasta que quede cremosa. No agregues sal ni limón.",
      "Para BLW: cortá gajos gruesos y pasalos por avena procesada para que no se resbalen.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-papilla-avena-banana",
    name: "Papilla de avena con banana",
    emoji: "🥣",
    description: "Desayuno con cereal (incluye gluten: es momento de introducirlo).",
    mealTypes: ["desayuno", "merienda"],
    tags: ["cereal", "gluten"],
    servings: 2,
    prep: 3,
    cook: 6,
    babyMinMonths: 6,
    babyTexture: "papilla",
    ingredients: [
      ["avena", 20, "procesada fina"],
      ["banana", 50],
    ],
    steps: [
      "Procesá la avena hasta que quede como harina.",
      "Cociná la avena con 120 ml de agua (o leche materna/fórmula fuera del fuego) 4-5 minutos revolviendo.",
      "Fuera del fuego sumá la banana pisada.",
      "Dejá entibiar y probá la temperatura antes de ofrecer.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-polenta-calabaza",
    name: "Polenta con calabaza",
    emoji: "🌽",
    description: "Cereal sin gluten, suave y rendidor.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["cereal", "sin gluten"],
    servings: 2,
    prep: 5,
    cook: 15,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [
      ["polenta", 20],
      ["zapallo", 100],
      ["aceite-oliva", 4],
    ],
    steps: [
      "Cociná la calabaza en cubos en 250 ml de agua hasta que esté tierna; retirala y pisala.",
      "En esa misma agua (150 ml), agregá la polenta en lluvia revolviendo y cociná 5 minutos.",
      "Mezclá con la calabaza pisada y el aceite. Sin sal.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-huevo-palta",
    name: "Huevo duro pisado con palta",
    emoji: "🥚",
    description: "Introducción del huevo (alérgeno): siempre bien cocido.",
    mealTypes: ["almuerzo", "cena", "desayuno"],
    tags: ["alérgeno: huevo", "hierro"],
    servings: 2,
    prep: 5,
    cook: 12,
    babyMinMonths: 6,
    babyTexture: "puré grumoso",
    ingredients: [
      ["huevo", 50],
      ["palta", 50],
    ],
    steps: [
      "Hervé el huevo 12 minutos (yema y clara bien firmes).",
      "Pelalo y pisalo bien fino con tenedor.",
      "Mezclalo con la palta pisada hasta lograr una crema.",
      "La primera vez ofrecé una cantidad chica, de día, y observá las siguientes 2 horas.",
    ],
    tips: "Ofrecé el huevo seguido (2-3 veces por semana) una vez introducido para mantener la tolerancia.",
  },
  {
    ...BASE,
    slug: "bebe-mani-banana",
    name: "Banana con pasta de maní diluida",
    emoji: "🥜",
    description: "Introducción temprana del maní (alérgeno). Nunca maní entero.",
    mealTypes: ["merienda", "desayuno"],
    tags: ["alérgeno: maní", "sin cocción"],
    servings: 1,
    prep: 3,
    cook: 0,
    babyMinMonths: 6,
    babyTexture: "puré liso",
    ingredients: [
      ["pasta-mani", 3, "1/4 cucharadita para empezar"],
      ["banana", 60],
    ],
    steps: [
      "Diluí la pasta de maní con 1 cucharadita de agua tibia hasta que quede líquida (nunca la des espesa: puede pegarse al paladar).",
      "Mezclala bien con la banana pisada.",
      "Primera vez: de día, en casa, cantidad chica y observando 2 horas.",
      "Si lo tolera bien, mantenelo en la dieta varias veces por semana.",
    ],
    tips: "Si hay eccema severo o alergia al huevo, consultá con el pediatra antes de introducir el maní.",
  },
  {
    ...BASE,
    slug: "bebe-bastones-batata",
    name: "Bastones de batata al horno (BLW)",
    emoji: "🍠",
    description: "Formato bastón del tamaño de un dedo adulto, blandos por dentro.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["BLW", "freezer"],
    servings: 3,
    prep: 5,
    cook: 25,
    babyMinMonths: 6,
    babyTexture: "BLW trozos blandos",
    ingredients: [
      ["batata", 200],
      ["aceite-oliva", 3],
    ],
    steps: [
      "Pelá la batata y cortala en bastones de 1,5 cm de ancho y unos 6 cm de largo.",
      "Pincelá con aceite y horneá a 190 °C 20-25 minutos, hasta que estén bien tiernos.",
      "Comprobá que se aplasten fácil entre tus dedos índice y pulgar.",
      "Dejá enfriar y ofrecé en la bandeja para que los agarre solo/a.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-brocoli-arbolitos",
    name: "Arbolitos de brócoli al vapor (BLW)",
    emoji: "🥦",
    description: "El tronquito funciona como mango.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["BLW"],
    servings: 2,
    prep: 3,
    cook: 8,
    babyMinMonths: 6,
    babyTexture: "BLW trozos blandos",
    ingredients: [["brocoli", 150]],
    steps: [
      "Cortá arbolitos grandes dejando un tronquito largo para agarrar.",
      "Cociná al vapor 7-8 minutos, hasta que estén bien tiernos (más que para un adulto).",
      "Verificá que se aplaste fácil con los dedos y dejá enfriar.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-tiras-pollo",
    name: "Tiras de pollo tiernas (BLW)",
    emoji: "🍗",
    description: "El muslo queda jugoso y se deshace fácil.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["BLW", "hierro"],
    servings: 3,
    prep: 5,
    cook: 25,
    babyMinMonths: 6,
    babyTexture: "BLW tiras",
    ingredients: [
      ["muslo-pollo", 120],
      ["aceite-oliva", 2],
    ],
    steps: [
      "Cociná el muslo al horno o hervido hasta que esté muy tierno y bien cocido.",
      "Desmenuzalo en tiras largas del tamaño de un dedo, sin piel ni huesos.",
      "Las fibras deben deshacerse fácil; si está seco, humedecelo con su caldo.",
    ],
    tips: "Revisá muy bien que no queden huesitos ni cartílagos.",
  },
  {
    ...BASE,
    slug: "bebe-omelette-tiras",
    name: "Omelette en tiras con zapallito (BLW)",
    emoji: "🍳",
    description: "Huevo bien cocido en formato fácil de agarrar.",
    mealTypes: ["almuerzo", "cena", "desayuno"],
    tags: ["BLW", "alérgeno: huevo"],
    servings: 2,
    prep: 5,
    cook: 8,
    babyMinMonths: 6,
    babyTexture: "BLW tiras",
    ingredients: [
      ["huevo", 50],
      ["zapallito", 40, "rallado"],
      ["aceite-oliva", 2],
    ],
    steps: [
      "Rallá el zapallito y escurrilo apretando con las manos.",
      "Batí el huevo y mezclalo con el zapallito.",
      "Cociná en sartén antiadherente a fuego bajo, tapado, hasta que esté completamente cocido (sin partes líquidas).",
      "Cortá en tiras de 1,5 cm de ancho.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-merluza-papa",
    name: "Merluza con puré de papa",
    emoji: "🐟",
    description: "Pescado blanco, suave y fácil de desmenuzar (alérgeno: pescado).",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alérgeno: pescado", "comida completa"],
    servings: 2,
    prep: 10,
    cook: 20,
    babyMinMonths: 6,
    babyTexture: "puré grumoso",
    ingredients: [
      ["merluza", 50],
      ["papa", 100],
      ["aceite-oliva", 4],
    ],
    steps: [
      "Hervé la papa en cubos 15 minutos.",
      "Cociná la merluza al vapor o hervida 6-8 minutos.",
      "Desmenuzá el pescado revisando MUY bien que no queden espinas.",
      "Pisá la papa con un poco del agua, sumá el pescado y el aceite.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-arroz-zapallo-pollo",
    name: "Arroz con calabaza y pollo",
    emoji: "🍚",
    description: "Texturas más grumosas para avanzar en la masticación.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["comida completa", "freezer"],
    servings: 3,
    prep: 10,
    cook: 25,
    babyMinMonths: 7,
    babyTexture: "puré grumoso",
    ingredients: [
      ["arroz-blanco", 25],
      ["zapallo", 100],
      ["pechuga-pollo", 40],
      ["aceite-oliva", 5],
    ],
    steps: [
      "Cociná el arroz en abundante agua 20 minutos (que quede pasado, muy blando).",
      "Cociná el pollo y la calabaza en agua sin sal.",
      "Picá el pollo muy fino y pisá la calabaza.",
      "Mezclá todo con el arroz pisándolo un poco. Agregá el aceite.",
    ],
    storage: "24 h en heladera o 1 mes en freezer.",
  },
  {
    ...BASE,
    slug: "bebe-lentejas-zanahoria",
    name: "Puré de lentejas con zanahoria",
    emoji: "🫘",
    description: "Legumbre con hierro vegetal; combinala con fruta con vitamina C de postre.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["hierro", "legumbres", "freezer"],
    servings: 3,
    prep: 10,
    cook: 30,
    babyMinMonths: 7,
    babyTexture: "puré liso",
    ingredients: [
      ["lentejas", 30, "remojadas"],
      ["zanahoria", 80],
      ["cebolla", 20],
      ["aceite-oliva", 5],
    ],
    steps: [
      "Remojá las lentejas desde la noche anterior y enjuagalas.",
      "Cocinalas con la zanahoria y la cebolla en agua sin sal 25-30 minutos, hasta que estén muy tiernas.",
      "Procesá bien (o pasá por pasapuré para quitar las pieles).",
      "Agregá el aceite al servir.",
    ],
    tips: "De postre, mandarina o naranja: la vitamina C ayuda a absorber el hierro.",
  },
  {
    ...BASE,
    slug: "bebe-higado-calabaza",
    name: "Hígado de pollo con puré de calabaza",
    emoji: "🧡",
    description: "Súper fuente de hierro. Máximo una vez por semana.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["hierro"],
    servings: 2,
    prep: 10,
    cook: 20,
    babyMinMonths: 7,
    babyTexture: "puré liso",
    ingredients: [
      ["higado-pollo", 25],
      ["zapallo", 100],
      ["papa", 50],
      ["aceite-oliva", 4],
    ],
    steps: [
      "Limpiá el hígado y cocinalo en agua 10 minutos, hasta que esté bien cocido por dentro.",
      "Cociná la calabaza y la papa en cubos.",
      "Procesá todo junto hasta que quede bien liso.",
      "Agregá el aceite al servir.",
    ],
    tips: "Por su alto contenido de vitamina A, ofrecé hígado como máximo 1 vez por semana.",
  },
  {
    ...BASE,
    slug: "bebe-pancakes-banana-avena",
    name: "Pancakes de banana y avena (BLW)",
    emoji: "🥞",
    description: "Sin azúcar ni harina. Fáciles de agarrar.",
    mealTypes: ["desayuno", "merienda"],
    tags: ["BLW", "alérgeno: huevo", "freezer"],
    servings: 2,
    prep: 5,
    cook: 8,
    babyMinMonths: 8,
    babyTexture: "BLW tiras",
    ingredients: [
      ["banana", 60],
      ["huevo", 50],
      ["avena", 20],
    ],
    steps: [
      "Pisá la banana y mezclala con el huevo batido y la avena.",
      "Cociná pequeñas porciones en sartén antiadherente a fuego bajo, 2 minutos por lado.",
      "Comprobá que estén cocidos por dentro.",
      "Cortá en tiras para que pueda agarrarlas.",
    ],
    storage: "Se freezan separados con papel manteca.",
  },
  {
    ...BASE,
    slug: "bebe-yogur-fruta",
    name: "Yogur natural con fruta pisada",
    emoji: "🍓",
    description: "Lácteo sin azúcar agregada; el dulzor lo da la fruta.",
    mealTypes: ["merienda", "desayuno"],
    tags: ["alérgeno: leche", "sin cocción"],
    servings: 1,
    prep: 3,
    cook: 0,
    babyMinMonths: 8,
    babyTexture: "puré liso",
    ingredients: [
      ["yogur-entero", 100],
      ["frutilla", 40],
    ],
    steps: [
      "Pisá bien la fruta (frutilla, durazno o banana).",
      "Mezclala con el yogur natural entero (sin azúcar, no descremado).",
    ],
  },
  {
    ...BASE,
    slug: "bebe-ricota-pera",
    name: "Ricota con pera",
    emoji: "🍐",
    description: "Merienda cremosa con calcio.",
    mealTypes: ["merienda", "desayuno"],
    tags: ["alérgeno: leche", "sin cocción"],
    servings: 1,
    prep: 3,
    cook: 0,
    babyMinMonths: 8,
    babyTexture: "puré grumoso",
    ingredients: [
      ["ricota", 40],
      ["pera", 80],
    ],
    steps: ["Pisá la pera madura (o cocida) y mezclala con la ricota."],
  },
  {
    ...BASE,
    slug: "bebe-albondiguitas-avena",
    name: "Albondiguitas de carne y avena (BLW)",
    emoji: "🧆",
    description: "Formato alargado tipo salchichita, ideales para agarrar.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["BLW", "hierro", "freezer"],
    servings: 4,
    prep: 15,
    cook: 20,
    babyMinMonths: 8,
    babyTexture: "BLW trozos blandos",
    ingredients: [
      ["carne-picada-magra", 100],
      ["avena", 15],
      ["zanahoria", 30, "rallada fina"],
      ["huevo", 25, "media unidad"],
      ["cebolla", 10, "rallada"],
    ],
    steps: [
      "Mezclá todos los ingredientes (sin sal).",
      "Formá cilindros del tamaño de un dedo.",
      "Horneá a 180 °C 18-20 minutos, o cociná en caldo casero sin sal.",
      "Verificá que estén bien cocidas por dentro y tiernas.",
    ],
    storage: "1 mes en freezer.",
  },
  {
    ...BASE,
    slug: "bebe-fideos-tuco-carne",
    name: "Fideítos con tuco casero y carne",
    emoji: "🍝",
    description: "Comida familiar adaptada (separá la porción antes de salar).",
    mealTypes: ["almuerzo", "cena"],
    tags: ["comida familiar", "alérgeno: gluten"],
    servings: 2,
    prep: 10,
    cook: 20,
    babyMinMonths: 9,
    babyTexture: "picado",
    ingredients: [
      ["fideos", 25, "dedalitos o municiones"],
      ["tomate-triturado", 60],
      ["carne-picada-magra", 30],
      ["zapallito", 40],
      ["aceite-oliva", 4],
    ],
    steps: [
      "Cociná la carne con el zapallito rallado y el tomate 15 minutos (sin sal).",
      "Hervé los fideos chicos hasta que estén bien tiernos.",
      "Mezclá todo y agregá el aceite.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-muffins-zapallo-avena",
    name: "Muffins de calabaza y avena (sin azúcar)",
    emoji: "🧁",
    description: "Para meriendas o para llevar. Rinde 8.",
    mealTypes: ["merienda", "desayuno"],
    tags: ["BLW", "freezer", "alérgeno: huevo"],
    servings: 8,
    prep: 15,
    cook: 25,
    babyMinMonths: 9,
    babyTexture: "BLW trozos blandos",
    ingredients: [
      ["zapallo", 150, "cocido y pisado"],
      ["avena", 80],
      ["huevo", 100],
      ["banana", 100],
      ["polvo-hornear", 4],
      ["aceite-girasol", 10],
      ["canela", 1],
    ],
    steps: [
      "Precalentá el horno a 180 °C.",
      "Pisá la calabaza cocida y la banana; mezclá con los huevos y el aceite.",
      "Sumá la avena procesada, el polvo de hornear y la canela.",
      "Repartí en 8 moldes y horneá 20-25 minutos.",
    ],
    storage: "3 días en heladera, 1 mes en freezer.",
  },
  {
    ...BASE,
    slug: "bebe-guiso-lentejas",
    name: "Guisito de lentejas con arroz (picado)",
    emoji: "🍲",
    description: "Versión bebé del guiso familiar.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["hierro", "legumbres", "comida familiar"],
    servings: 3,
    prep: 10,
    cook: 35,
    babyMinMonths: 9,
    babyTexture: "picado",
    ingredients: [
      ["lentejas", 30],
      ["arroz-blanco", 15],
      ["zanahoria", 40],
      ["zapallo", 40],
      ["carne-picada-magra", 20],
      ["tomate", 20],
      ["aceite-oliva", 4],
    ],
    steps: [
      "Cociná la carne con la zanahoria y la calabaza en cubitos y el tomate pelado.",
      "Sumá las lentejas remojadas, el arroz y agua; cociná 30 minutos hasta que todo esté muy tierno.",
      "Pisá un poco con tenedor dejando trocitos blandos.",
      "Agregá el aceite al servir.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-tortitas-brocoli",
    name: "Tortitas de brócoli y queso (BLW)",
    emoji: "🥦",
    description: "Para que la verdura sea fácil de agarrar.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["BLW", "alérgeno: huevo", "alérgeno: leche"],
    servings: 3,
    prep: 10,
    cook: 15,
    babyMinMonths: 9,
    babyTexture: "BLW trozos blandos",
    ingredients: [
      ["brocoli", 100],
      ["huevo", 50],
      ["queso-rallado", 8],
      ["avena", 20],
    ],
    steps: [
      "Cociná el brócoli al vapor y picalo bien fino.",
      "Mezclá con el huevo, el queso y la avena.",
      "Formá tortitas y cocinalas en sartén antiadherente o al horno hasta que estén firmes.",
    ],
  },
  {
    ...BASE,
    slug: "bebe-croquetas-merluza",
    name: "Croquetas de merluza al horno",
    emoji: "🐠",
    description: "Pescado en formato BLW, sin fritura.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["BLW", "alérgeno: pescado", "freezer"],
    servings: 3,
    prep: 15,
    cook: 25,
    babyMinMonths: 9,
    babyTexture: "BLW trozos blandos",
    ingredients: [
      ["merluza", 100],
      ["papa", 100],
      ["huevo", 25],
      ["perejil", 2],
    ],
    steps: [
      "Hervé la papa y la merluza. Desmenuzá el pescado revisando que no tenga espinas.",
      "Pisá la papa y mezclala con el pescado, el huevo y el perejil picado.",
      "Formá croquetas alargadas y horneá a 190 °C 15-20 minutos.",
    ],
  },
];
