import type { RecipeSeed } from "./recipes";

/** Segunda tanda de recetas (seed v2): clásicos argentinos en versión liviana. */
export const EXTRA_RECIPES: RecipeSeed[] = [
  {
    slug: "empanadas-pollo-horno",
    name: "Empanadas de pollo al horno",
    emoji: "🥟",
    description: "Las de siempre, al horno y con relleno magro. 3 empanadas por porción.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["freezer", "finde", "alto en proteína"],
    servings: 4,
    prep: 30,
    cook: 20,
    difficulty: "media",
    ingredients: [
      ["tapa-empanada", 396, "12 tapas"],
      ["pechuga-pollo", 400],
      ["cebolla", 300],
      ["morron-rojo", 150],
      ["huevo", 100, "2 duros"],
      ["aceite-girasol", 10],
      ["pimenton", 3],
      ["comino", 1],
      ["sal", 3],
    ],
    steps: [
      "Hervé la pechuga 15 minutos, dejala entibiar y desmenuzala o picala chiquita.",
      "Rehogá la cebolla y el morrón picados con el aceite hasta que estén bien tiernos.",
      "Sumá el pollo, el pimentón, el comino y la sal. Mezclá y dejá enfriar el relleno.",
      "Agregá el huevo duro picado.",
      "Rellená las tapas, cerralas con repulgue o apretando con un tenedor y pincelalas con un poco de huevo batido.",
      "Horneá a 220 °C entre 15 y 20 minutos, hasta que estén doradas.",
    ],
    tips: "Si el relleno está frío, las empanadas no se rompen al armarlas.",
    storage: "Crudas se freezan en bandeja y después en bolsa; van directo al horno.",
  },
  {
    slug: "revuelto-gramajo-light",
    name: "Revuelto gramajo light",
    emoji: "🍳",
    description: "El clásico de bodegón con papas al horno en vez de fritas y más claras.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "rápido"],
    servings: 2,
    prep: 10,
    cook: 30,
    ingredients: [
      ["papa", 400, "en bastones finos"],
      ["huevo", 200, "4 unidades"],
      ["clara-huevo", 132, "4 claras"],
      ["jamon-cocido", 80],
      ["cebolla", 100],
      ["arvejas-lata", 100],
      ["aceite-girasol", 10],
      ["sal", 2],
    ],
    steps: [
      "Cortá las papas en bastones finos, mezclalas con la mitad del aceite y sal, y horneá a 220 °C 25 minutos, dando vuelta a mitad.",
      "En una sartén grande, rehogá la cebolla en pluma con el resto del aceite.",
      "Sumá el jamón en tiras y las arvejas escurridas.",
      "Agregá los huevos y las claras batidas y revolvé a fuego bajo hasta que estén apenas cremosos.",
      "Mezclá con las papas al horno y serví enseguida.",
    ],
  },
  {
    slug: "milanesas-berenjena-horno",
    name: "Milanesas de berenjena al horno",
    emoji: "🍆",
    description: "Opción veggie crocante para acompañar con ensalada o puré.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["vegetariano", "freezer"],
    servings: 3,
    prep: 20,
    cook: 25,
    ingredients: [
      ["berenjena", 500, "en rodajas de 1 cm"],
      ["huevo", 100],
      ["pan-rallado", 70],
      ["queso-rallado", 15],
      ["ajo", 5],
      ["perejil", 8],
      ["aceite-oliva", 5],
      ["sal", 2],
    ],
    steps: [
      "Cortá la berenjena en rodajas, salala y dejala 15 minutos para que largue el amargor. Secala con papel.",
      "Batí los huevos con ajo y perejil picados.",
      "Mezclá el pan rallado con el queso rallado.",
      "Pasá cada rodaja por huevo y después por el pan rallado.",
      "Acomodá en una placa aceitada y horneá a 200 °C 10-12 minutos por lado.",
    ],
    tips: "Gratinadas con salsa de tomate y un poco de queso quedan tipo napolitana.",
    storage: "Crudas empanadas se freezan perfecto.",
  },
  {
    slug: "tarta-atun-cebolla",
    name: "Tarta de atún y cebolla (una tapa)",
    emoji: "🥧",
    description: "Tarta abierta, rendidora y alta en proteína.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "meal prep"],
    servings: 4,
    prep: 15,
    cook: 35,
    ingredients: [
      ["tapa-tarta", 180, "1 tapa"],
      ["atun-lata", 240, "2 latas"],
      ["cebolla", 300],
      ["morron-rojo", 150],
      ["huevo", 150, "3 unidades"],
      ["aceite-oliva", 5],
      ["oregano", 1],
      ["sal", 2],
    ],
    steps: [
      "Forrá una tartera con la tapa y precalentá el horno a 180 °C.",
      "Rehogá la cebolla y el morrón en tiras con el aceite hasta que estén bien tiernos.",
      "Fuera del fuego, mezclá con el atún escurrido, los huevos batidos, orégano y sal.",
      "Rellená la tarta y horneá 30-35 minutos hasta que esté firme.",
      "Cortá en 4 porciones.",
    ],
    storage: "3 días en heladera.",
  },
  {
    slug: "pollo-limon-papas",
    name: "Pollo al limón con papas al horno",
    emoji: "🍋",
    description: "Muslos jugosos con limón y ajo, todo en una asadera.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "meal prep", "sin gluten"],
    servings: 4,
    prep: 15,
    cook: 45,
    ingredients: [
      ["muslo-pollo", 600],
      ["papa", 600],
      ["limon", 100, "jugo y ralladura"],
      ["ajo", 10],
      ["aceite-oliva", 15],
      ["oregano", 2],
      ["sal", 3],
    ],
    steps: [
      "Mezclá el jugo y la ralladura de limón con el ajo picado, el orégano, la sal y el aceite.",
      "Marinalo con los muslos al menos 20 minutos.",
      "Cortá las papas en gajos y acomodalas en una asadera con el pollo y la marinada.",
      "Horneá a 200 °C 40-45 minutos, dando vuelta a mitad, hasta que el pollo esté dorado y bien cocido.",
    ],
    storage: "4 días en heladera.",
  },
  {
    slug: "merluza-papillote",
    name: "Merluza en papillote con verduras",
    emoji: "🐟",
    description: "Pescado al vapor en su propio paquetito: cero enchastre y muy liviano.",
    mealTypes: ["cena", "almuerzo"],
    tags: ["bajo en grasa", "alto en proteína", "sin gluten"],
    servings: 4,
    prep: 15,
    cook: 20,
    ingredients: [
      ["merluza", 600],
      ["zanahoria", 200, "en juliana"],
      ["zapallito", 300, "en juliana"],
      ["cebolla", 150],
      ["limon", 50],
      ["aceite-oliva", 10],
      ["sal", 2],
      ["pimienta", 0.5],
    ],
    steps: [
      "Cortá las verduras en tiras finas.",
      "Sobre 4 hojas de papel manteca (o aluminio), poné una cama de verduras, encima el filet, sal, pimienta, rodajas de limón y un hilo de aceite.",
      "Cerrá bien los paquetes doblando los bordes.",
      "Horneá a 200 °C 18-20 minutos. Abrí con cuidado: sale vapor caliente.",
    ],
  },
  {
    slug: "bowl-quinoa-garbanzos",
    name: "Bowl de quinoa, garbanzos y vegetales asados",
    emoji: "🥙",
    description: "Plato veggie completo, ideal para viandas.",
    mealTypes: ["almuerzo"],
    tags: ["vegetariano", "alto en fibra", "meal prep", "sin gluten"],
    servings: 3,
    prep: 15,
    cook: 30,
    ingredients: [
      ["quinoa", 160],
      ["garbanzos-lata", 240],
      ["zapallo", 300],
      ["morron-rojo", 150],
      ["cebolla-morada", 100],
      ["rucula", 60],
      ["aceite-oliva", 15],
      ["limon", 20],
      ["comino", 1],
      ["sal", 2],
    ],
    steps: [
      "Lavá muy bien la quinoa y cocinala en el doble de agua 15 minutos.",
      "Asá la calabaza en cubos, el morrón y la cebolla con 10 g de aceite, comino y sal (200 °C, 25 minutos).",
      "Sumá los garbanzos escurridos a la placa los últimos 10 minutos para que se doren.",
      "Armá el bowl: quinoa, vegetales asados, garbanzos y rúcula. Condimentá con el resto del aceite y limón.",
    ],
    storage: "3 días en heladera (la rúcula agregala al momento).",
  },
  {
    slug: "guiso-arroz-carne",
    name: "Guiso de arroz con carne y verduras",
    emoji: "🍲",
    description: "Comida de olla, rendidora y reconfortante.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["meal prep", "freezer", "post-entreno"],
    servings: 5,
    prep: 20,
    cook: 40,
    ingredients: [
      ["arroz-blanco", 240],
      ["nalga", 400, "en cubos"],
      ["cebolla", 150],
      ["morron-rojo", 150],
      ["zanahoria", 150],
      ["arvejas-lata", 150],
      ["tomate-triturado", 260],
      ["pimenton", 3],
      ["laurel", 0.2],
      ["aceite-girasol", 10],
      ["sal", 4],
    ],
    steps: [
      "Sellá la carne en cubos con el aceite y retirala.",
      "Rehogá cebolla, morrón y zanahoria picados 5 minutos.",
      "Volvé a poner la carne, sumá pimentón, laurel, tomate y 1 litro de agua caliente. Cociná 20 minutos.",
      "Agregá el arroz y cociná 15-18 minutos más, revolviendo de vez en cuando y sumando agua si hace falta.",
      "Al final sumá las arvejas y ajustá la sal. Rinde 5 platos.",
    ],
    storage: "4 días en heladera; se freeza bien.",
  },
  {
    slug: "ensalada-tibia-lentejas",
    name: "Ensalada tibia de lentejas",
    emoji: "🥗",
    description: "Legumbres, verduras y huevo: proteína vegetal en 15 minutos.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["vegetariano", "alto en fibra", "rápido"],
    servings: 3,
    prep: 15,
    cook: 10,
    ingredients: [
      ["lentejas-lata", 480, "2 latas"],
      ["tomate", 200],
      ["cebolla-morada", 50],
      ["morron-rojo", 100],
      ["huevo", 100, "2 duros"],
      ["aceite-oliva", 10],
      ["vinagre", 10],
      ["perejil", 8],
      ["sal", 1],
    ],
    steps: [
      "Enjuagá las lentejas y calentalas 2 minutos en una sartén.",
      "Picá el tomate, la cebolla, el morrón y el perejil.",
      "Mezclá todo con las lentejas tibias y condimentá con aceite, vinagre y sal.",
      "Serví con el huevo duro en cuartos.",
    ],
  },
  {
    slug: "tostada-mani-banana",
    name: "Tostada con pasta de maní y banana",
    emoji: "🍞",
    description: "Pre-entreno rápido con energía y algo de proteína.",
    mealTypes: ["desayuno", "merienda", "snack"],
    tags: ["rápido", "pre-entreno", "vegetariano"],
    servings: 1,
    prep: 3,
    cook: 2,
    ingredients: [
      ["pan-integral", 25, "1 rebanada"],
      ["pasta-mani", 10],
      ["banana", 60],
    ],
    steps: ["Tostá el pan.", "Untá la pasta de maní y cubrí con rodajas de banana."],
  },
  {
    slug: "chocolatada-light",
    name: "Chocolatada light",
    emoji: "🍫",
    description: "Para el antojo dulce de la tarde, con muy pocas calorías.",
    mealTypes: ["merienda", "snack", "desayuno"],
    tags: ["rápido", "sin azúcar"],
    servings: 1,
    prep: 3,
    cook: 2,
    ingredients: [
      ["leche-descremada", 250],
      ["cacao", 8],
      ["edulcorante", 0.2, "a gusto"],
    ],
    steps: ["Disolvé el cacao en un poco de leche caliente.", "Sumá el resto de la leche y el edulcorante. Se puede tomar fría o caliente."],
  },
];
