/**
 * Recetario inicial para adultos, pensado para déficit calórico:
 * porciones medidas, mucha verdura, proteína en cada comida y poco aceite.
 * Los gramos son del total de la receta (crudos); las calorías por porción
 * se calculan automáticamente a partir de los ingredientes.
 */

export type RecipeSeed = {
  slug: string;
  name: string;
  emoji: string;
  description: string;
  audience?: "adult" | "baby";
  mealTypes: string[];
  tags: string[];
  servings: number;
  prep: number;
  cook: number;
  difficulty?: "fácil" | "media" | "difícil";
  ingredients: [slug: string, grams: number, note?: string][];
  steps: string[];
  tips?: string;
  storage?: string;
  babyMinMonths?: number;
  babyTexture?: string;
};

export const ADULT_RECIPES: RecipeSeed[] = [
  /* ============================ DESAYUNOS / MERIENDAS ============================ */
  {
    slug: "avena-cocida-banana",
    name: "Avena cocida con banana y canela",
    emoji: "🥣",
    description: "Desayuno cremoso, saciante y rápido. Ideal para días de entrenamiento.",
    mealTypes: ["desayuno", "merienda"],
    tags: ["rápido", "vegetariano", "alto en fibra"],
    servings: 1,
    prep: 2,
    cook: 6,
    ingredients: [
      ["avena", 40],
      ["leche-descremada", 200],
      ["banana", 60, "en rodajas"],
      ["canela", 1],
      ["chia", 5],
    ],
    steps: [
      "Poné la avena y la leche en una ollita a fuego medio.",
      "Revolvé durante 4-5 minutos hasta que espese (si queda muy espesa, agregá un chorrito de agua).",
      "Apagá el fuego y sumá la canela y, si querés, unas gotas de edulcorante.",
      "Serví en un bowl y coroná con la banana en rodajas y las semillas de chía.",
    ],
    tips: "Si la preparás la noche anterior en frío (overnight oats) queda lista para llevar.",
    storage: "Mejor recién hecha. En frío dura 2 días en heladera.",
  },
  {
    slug: "omelette-espinaca-queso",
    name: "Omelette de espinaca y queso",
    emoji: "🍳",
    description: "Alto en proteína y muy bajo en carbohidratos. Sirve de desayuno o cena liviana.",
    mealTypes: ["desayuno", "cena"],
    tags: ["alto en proteína", "rápido", "bajo en carbohidratos", "vegetariano"],
    servings: 1,
    prep: 5,
    cook: 6,
    ingredients: [
      ["huevo", 100, "2 unidades"],
      ["clara-huevo", 33, "1 clara"],
      ["espinaca", 50],
      ["queso-cremoso-light", 20],
      ["aceite-oliva", 3],
      ["sal", 0.5],
      ["pimienta", 0.2],
    ],
    steps: [
      "Lavá la espinaca y picala grueso.",
      "Batí los huevos y la clara con sal y pimienta.",
      "En una sartén antiadherente con el aceite, saltá la espinaca 1 minuto hasta que baje.",
      "Volcá el huevo batido, bajá el fuego y dejá que cuaje 2-3 minutos.",
      "Poné el queso en cubitos sobre una mitad, doblá el omelette y cociná 1 minuto más.",
    ],
    tips: "Podés sumar champiñones, tomate o cebolla de verdeo sin casi sumar calorías.",
  },
  {
    slug: "tostadas-palta-huevo",
    name: "Tostadas integrales con palta y huevo",
    emoji: "🥑",
    description: "Grasas buenas, proteína y fibra para arrancar el día.",
    mealTypes: ["desayuno", "merienda"],
    tags: ["rápido", "vegetariano"],
    servings: 1,
    prep: 5,
    cook: 8,
    ingredients: [
      ["pan-integral", 50, "2 rebanadas"],
      ["palta", 40],
      ["huevo", 50, "1 unidad"],
      ["limon", 5, "unas gotas"],
      ["sal", 0.3],
    ],
    steps: [
      "Hervé el huevo 8 minutos (o hacelo a la plancha / poché).",
      "Tostá las rebanadas de pan.",
      "Pisá la palta con unas gotas de limón y una pizca de sal.",
      "Untá las tostadas con la palta y poné el huevo en rodajas arriba.",
    ],
    tips: "Pimienta, ají molido o semillas de sésamo le dan un plus.",
  },
  {
    slug: "bowl-yogur-frutas-avena",
    name: "Bowl de yogur con frutas y avena",
    emoji: "🍓",
    description: "Fresco, dulce y liviano. Perfecto para la merienda.",
    mealTypes: ["desayuno", "merienda"],
    tags: ["rápido", "sin cocción", "vegetariano"],
    servings: 1,
    prep: 3,
    cook: 0,
    ingredients: [
      ["yogur-descremado", 190, "1 pote"],
      ["avena", 20],
      ["frutilla", 80],
      ["chia", 5],
    ],
    steps: [
      "Poné el yogur en un bowl.",
      "Cortá las frutillas (o la fruta de estación que tengas).",
      "Sumá la avena, la fruta y las semillas de chía por encima.",
    ],
    tips: "Si querés más proteína, usá yogur griego (sube unas 50 kcal).",
  },
  {
    slug: "pancakes-avena-banana",
    name: "Pancakes de avena y banana",
    emoji: "🥞",
    description: "Sin harina ni azúcar. Dulces gracias a la banana bien madura.",
    mealTypes: ["desayuno", "merienda"],
    tags: ["vegetariano", "sin azúcar"],
    servings: 1,
    prep: 5,
    cook: 10,
    ingredients: [
      ["avena", 40],
      ["banana", 100, "bien madura"],
      ["huevo", 50],
      ["polvo-hornear", 2],
      ["canela", 1],
      ["aceite-girasol", 2, "para la sartén"],
    ],
    steps: [
      "Procesá o licuá la avena hasta que quede como harina.",
      "Pisá la banana y mezclala con el huevo, la avena, el polvo de hornear y la canela.",
      "Calentá una sartén antiadherente y pincelala apenas con aceite.",
      "Poné cucharadas de mezcla y cociná 2 minutos por lado a fuego medio-bajo.",
      "Serví con fruta fresca o una cucharada de yogur.",
    ],
    storage: "Se pueden freezar separados con papel manteca y recalentar en tostadora.",
  },
  {
    slug: "licuado-banana-avena",
    name: "Licuado de banana, leche y avena",
    emoji: "🥤",
    description: "Ideal post-entreno o para un desayuno al paso.",
    mealTypes: ["desayuno", "merienda", "snack"],
    tags: ["rápido", "post-entreno", "vegetariano"],
    servings: 1,
    prep: 3,
    cook: 0,
    ingredients: [
      ["leche-descremada", 250],
      ["banana", 100],
      ["avena", 15],
      ["cacao", 5],
      ["canela", 0.5],
    ],
    steps: [
      "Poné todos los ingredientes en la licuadora.",
      "Licuá 1 minuto hasta que quede bien cremoso.",
      "Si lo querés frío, agregá 3-4 cubitos de hielo.",
    ],
  },
  {
    slug: "tostadas-ricota-tomate",
    name: "Tostadas con ricota, tomate y orégano",
    emoji: "🍅",
    description: "Clásico liviano para la merienda.",
    mealTypes: ["desayuno", "merienda"],
    tags: ["rápido", "vegetariano"],
    servings: 1,
    prep: 5,
    cook: 2,
    ingredients: [
      ["pan-integral", 50, "2 rebanadas"],
      ["ricota", 60],
      ["tomate", 80, "en rodajas"],
      ["oregano", 0.5],
      ["sal", 0.2],
    ],
    steps: [
      "Tostá el pan.",
      "Untá cada tostada con ricota.",
      "Cubrí con rodajas de tomate, orégano y una pizca de sal.",
    ],
  },
  {
    slug: "budin-avena-manzana",
    name: "Budín de avena y manzana (sin azúcar)",
    emoji: "🍎",
    description: "Para hacer el domingo y tener meriendas toda la semana.",
    mealTypes: ["merienda", "desayuno", "snack"],
    tags: ["meal prep", "vegetariano", "sin azúcar"],
    servings: 8,
    prep: 15,
    cook: 40,
    difficulty: "media",
    ingredients: [
      ["avena", 200],
      ["huevo", 150, "3 unidades"],
      ["manzana", 360, "2 unidades ralladas"],
      ["leche-descremada", 150],
      ["polvo-hornear", 10],
      ["canela", 3],
      ["esencia-vainilla", 4],
      ["aceite-girasol", 20],
      ["edulcorante", 1, "a gusto"],
    ],
    steps: [
      "Precalentá el horno a 180 °C y aceitá una budinera.",
      "Procesá la mitad de la avena para que quede como harina.",
      "Batí los huevos con la leche, el aceite, la vainilla y el edulcorante.",
      "Agregá la manzana rallada, la avena (procesada y entera), la canela y el polvo de hornear.",
      "Volcá en la budinera y horneá 35-40 minutos hasta que al pinchar salga seco.",
      "Dejá enfriar antes de cortar en 8 porciones.",
    ],
    storage: "5 días en heladera en recipiente cerrado. Se puede freezar en porciones.",
  },
  {
    slug: "muffins-huevo-verduras",
    name: "Muffins de huevo y verduras",
    emoji: "🧁",
    description: "Snack proteico para llevar. Rinde 6 unidades.",
    mealTypes: ["desayuno", "snack", "merienda"],
    tags: ["meal prep", "alto en proteína", "bajo en carbohidratos", "vegetariano"],
    servings: 6,
    prep: 10,
    cook: 22,
    ingredients: [
      ["huevo", 300, "6 unidades"],
      ["espinaca", 100],
      ["morron-rojo", 100],
      ["cebolla", 80],
      ["queso-cremoso-light", 60],
      ["sal", 1],
      ["pimienta", 0.3],
    ],
    steps: [
      "Precalentá el horno a 180 °C y aceitá un molde de muffins (o usá pirotines de silicona).",
      "Picá bien chiquito la cebolla, el morrón y la espinaca.",
      "Batí los huevos con sal y pimienta.",
      "Repartí las verduras y el queso en cubitos en 6 moldes y cubrí con el huevo.",
      "Horneá 20-22 minutos hasta que estén firmes y doraditos.",
    ],
    storage: "4 días en heladera. Se recalientan 30 segundos en microondas.",
  },
  {
    slug: "pudding-chia-frutos-rojos",
    name: "Pudding de chía con frutos rojos",
    emoji: "🫐",
    description: "Se prepara la noche anterior. Muy saciante.",
    mealTypes: ["desayuno", "merienda", "snack"],
    tags: ["sin cocción", "meal prep", "vegetariano"],
    servings: 1,
    prep: 5,
    cook: 0,
    ingredients: [
      ["chia", 20],
      ["leche-descremada", 150],
      ["arandanos", 50],
      ["esencia-vainilla", 2],
      ["edulcorante", 0.2, "a gusto"],
    ],
    steps: [
      "Mezclá la chía con la leche, la vainilla y el edulcorante en un frasco.",
      "Revolvé bien, esperá 5 minutos y volvé a revolver para que no se formen grumos.",
      "Tapá y dejá en la heladera mínimo 4 horas (ideal toda la noche).",
      "Serví con los arándanos o la fruta que tengas.",
    ],
    storage: "3 días en heladera.",
  },
  {
    slug: "wrap-desayuno-huevo-jamon",
    name: "Wrap de huevo, claras y jamón",
    emoji: "🌯",
    description: "Desayuno salado alto en proteína.",
    mealTypes: ["desayuno", "cena"],
    tags: ["alto en proteína", "rápido"],
    servings: 1,
    prep: 5,
    cook: 5,
    ingredients: [
      ["tortilla-integral", 40, "1 unidad"],
      ["huevo", 50],
      ["clara-huevo", 66, "2 claras"],
      ["jamon-cocido", 30, "2 fetas"],
      ["tomate", 40],
      ["sal", 0.3],
    ],
    steps: [
      "Batí el huevo con las claras y una pizca de sal.",
      "Hacé un revuelto en sartén antiadherente.",
      "Calentá la tortilla 20 segundos por lado.",
      "Rellená con el revuelto, el jamón y el tomate en cubos. Enrollá y cortá al medio.",
    ],
  },

  /* ============================ ALMUERZOS / CENAS ============================ */
  {
    slug: "pollo-horno-calabaza-batata",
    name: "Pollo al horno con calabaza y batata",
    emoji: "🍗",
    description: "Todo en una asadera: proteína magra y hidratos de buena calidad.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["meal prep", "alto en proteína", "sin gluten"],
    servings: 4,
    prep: 15,
    cook: 40,
    ingredients: [
      ["pechuga-pollo", 600],
      ["zapallo", 600, "en cubos"],
      ["batata", 400, "en cubos"],
      ["cebolla", 150, "en gajos"],
      ["aceite-oliva", 20],
      ["pimenton", 4],
      ["oregano", 2],
      ["ajo", 10, "2 dientes"],
      ["sal", 3],
    ],
    steps: [
      "Precalentá el horno a 200 °C.",
      "Cortá la calabaza y la batata en cubos de 2-3 cm y la cebolla en gajos.",
      "Cortá la pechuga en trozos grandes y condimentala con pimentón, orégano, ajo picado y sal.",
      "Poné todo en una asadera, rociá con el aceite y mezclá con las manos para que se impregne.",
      "Horneá 35-40 minutos, dando vuelta a mitad de cocción, hasta que las verduras estén tiernas y doradas.",
      "Dividí en 4 porciones iguales.",
    ],
    storage: "4 días en heladera. Ideal para viandas.",
  },
  {
    slug: "milanesas-pollo-horno-ensalada",
    name: "Milanesas de pollo al horno con ensalada",
    emoji: "🥗",
    description: "La milanesa de siempre pero al horno, con ensalada mixta.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "freezer"],
    servings: 4,
    prep: 25,
    cook: 20,
    difficulty: "media",
    ingredients: [
      ["pechuga-pollo", 500, "en filetes finos"],
      ["huevo", 50],
      ["pan-rallado", 80],
      ["ajo", 5],
      ["perejil", 10],
      ["lechuga", 300],
      ["tomate", 300],
      ["zanahoria", 100, "rallada"],
      ["aceite-oliva", 10, "para la ensalada"],
      ["sal", 2],
    ],
    steps: [
      "Fileteá las pechugas finitas (o pedilas así en la carnicería).",
      "Batí el huevo con ajo y perejil picados y una pizca de sal.",
      "Pasá cada filete por el huevo y después por el pan rallado, presionando bien.",
      "Horneá en placa aceitada (o con papel manteca) a 200 °C, 10 minutos por lado.",
      "Mientras, armá la ensalada de lechuga, tomate y zanahoria rallada; condimentá con el aceite, sal y limón o vinagre.",
      "Dividí milanesas y ensalada en 4 platos.",
    ],
    tips: "Para que queden más crocantes, mezclá el pan rallado con un poco de avena.",
    storage: "Crudas empanadas se freezan perfecto separadas con nylon.",
  },
  {
    slug: "wok-pollo-vegetales-arroz",
    name: "Wok de pollo y vegetales con arroz",
    emoji: "🥢",
    description: "Salteado rápido estilo oriental, lleno de color.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "meal prep"],
    servings: 4,
    prep: 15,
    cook: 20,
    ingredients: [
      ["pechuga-pollo", 400, "en tiras"],
      ["arroz-blanco", 160],
      ["morron-rojo", 150],
      ["zanahoria", 100],
      ["cebolla", 150],
      ["brocoli", 200],
      ["salsa-soja", 30],
      ["aceite-girasol", 10],
      ["ajo", 5],
    ],
    steps: [
      "Cociná el arroz en abundante agua con sal (12-15 minutos) y escurrilo.",
      "Cortá las verduras en juliana (tiras finas) y el brócoli en arbolitos.",
      "En un wok o sartén grande bien caliente con el aceite, dorá el pollo en tiras 5-6 minutos. Retiralo.",
      "Saltá la cebolla, el ajo, la zanahoria y el morrón 3 minutos a fuego fuerte.",
      "Sumá el brócoli y 2 cucharadas de agua; tapá 2 minutos.",
      "Volvé a agregar el pollo, la salsa de soja y el arroz. Mezclá 1 minuto y serví.",
    ],
    storage: "3 días en heladera.",
  },
  {
    slug: "albondigas-salsa-pure-zapallo",
    name: "Albóndigas en salsa con puré de calabaza",
    emoji: "🧆",
    description: "Comida casera reconfortante, con carne magra y puré liviano.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["meal prep", "freezer", "alto en proteína"],
    servings: 4,
    prep: 20,
    cook: 35,
    difficulty: "media",
    ingredients: [
      ["carne-picada-magra", 500],
      ["huevo", 50],
      ["avena", 30],
      ["cebolla", 150],
      ["ajo", 5],
      ["tomate-triturado", 520],
      ["zapallo", 800],
      ["oregano", 1],
      ["nuez-moscada", 0.3],
      ["sal", 3],
    ],
    steps: [
      "Mezclá la carne con el huevo, la avena, la mitad de la cebolla picadita, ajo y sal. Formá albóndigas chicas.",
      "En una olla, rehogá el resto de la cebolla con 2 cucharadas de agua (sin aceite) hasta que esté transparente.",
      "Sumá el tomate triturado, orégano, sal y medio vaso de agua. Cuando hierva, agregá las albóndigas.",
      "Cociná tapado a fuego bajo 20-25 minutos, moviendo la olla cada tanto.",
      "Mientras, hervé la calabaza en cubos 15 minutos, escurrí y hacé puré con sal y nuez moscada.",
      "Serví 1/4 del puré con 1/4 de las albóndigas y salsa.",
    ],
    storage: "4 días en heladera; las albóndigas en salsa se freezan hasta 3 meses.",
  },
  {
    slug: "bife-nalga-papas-ensalada",
    name: "Bife de nalga con papas al horno y ensalada",
    emoji: "🥩",
    description: "Un clásico argentino en versión porcionada.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "sin gluten"],
    servings: 1,
    prep: 10,
    cook: 30,
    ingredients: [
      ["nalga", 180],
      ["papa", 150],
      ["lechuga", 80],
      ["tomate", 120],
      ["cebolla", 40],
      ["aceite-oliva", 8],
      ["vinagre", 5],
      ["sal", 1],
    ],
    steps: [
      "Cortá la papa en gajos, condimentá con sal, romero u orégano y 3 g de aceite. Horneá 25-30 minutos a 200 °C.",
      "Armá la ensalada con lechuga, tomate y cebolla en pluma; condimentá con el resto del aceite, vinagre y sal.",
      "Calentá bien una plancha o sartén y cociná el bife 3-4 minutos por lado (según el punto que te guste).",
      "Dejá reposar el bife 2 minutos antes de cortar y serví con las papas y la ensalada.",
    ],
  },
  {
    slug: "merluza-horno-pure-mixto",
    name: "Merluza al horno con puré de papa y calabaza",
    emoji: "🐟",
    description: "Pescado blanco súper magro con un puré suave.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "bajo en grasa"],
    servings: 4,
    prep: 15,
    cook: 25,
    ingredients: [
      ["merluza", 600],
      ["limon", 50, "jugo"],
      ["ajo", 5],
      ["perejil", 10],
      ["aceite-oliva", 10],
      ["papa", 400],
      ["zapallo", 400],
      ["leche-descremada", 100],
      ["sal", 3],
    ],
    steps: [
      "Hervé la papa y la calabaza en cubos 15-20 minutos hasta que estén tiernas.",
      "Mientras, poné los filetes en una fuente, con jugo de limón, ajo y perejil picados, sal y el aceite.",
      "Horneá el pescado a 200 °C durante 12-15 minutos (se desarma fácil cuando está listo).",
      "Escurrí las verduras y pisalas con la leche caliente y sal hasta tener un puré liso.",
      "Serví cada filete con una porción de puré.",
    ],
    storage: "2 días en heladera (el pescado es mejor recién hecho).",
  },
  {
    slug: "tarta-zapallitos-light",
    name: "Tarta de zapallitos light (una sola tapa)",
    emoji: "🥧",
    description: "Tarta abierta, con mucho relleno y poca masa.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["vegetariano", "meal prep"],
    servings: 4,
    prep: 20,
    cook: 35,
    difficulty: "media",
    ingredients: [
      ["tapa-tarta", 180, "1 tapa"],
      ["zapallito", 800],
      ["cebolla", 150],
      ["huevo", 150, "3 unidades"],
      ["queso-cremoso-light", 100],
      ["queso-rallado", 20],
      ["sal", 3],
      ["nuez-moscada", 0.3],
    ],
    steps: [
      "Precalentá el horno a 180 °C y forrá una tartera con la tapa.",
      "Rallá o cortá los zapallitos en cubos chicos y picá la cebolla.",
      "Saltá la cebolla con un chorrito de agua, sumá los zapallitos y cociná hasta que pierdan el agua (10 minutos). Salpimentá.",
      "Dejá entibiar, mezclá con los huevos batidos, el queso cremoso en cubos y la nuez moscada.",
      "Rellená la tarta, espolvoreá con el queso rallado y horneá 30-35 minutos hasta que esté firme y dorada.",
      "Cortá en 4 porciones (cada porción = 1/4 de tarta).",
    ],
    tips: "Acompañá con una ensalada verde para sumar volumen sin calorías.",
    storage: "4 días en heladera.",
  },
  {
    slug: "tortilla-papa-espinaca-horno",
    name: "Tortilla de papa y espinaca al horno",
    emoji: "🥔",
    description: "Sin fritura: las papas se hacen al horno.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["vegetariano", "sin gluten", "meal prep"],
    servings: 4,
    prep: 15,
    cook: 40,
    ingredients: [
      ["papa", 600],
      ["espinaca", 300],
      ["cebolla", 150],
      ["huevo", 250, "5 unidades"],
      ["aceite-oliva", 10],
      ["sal", 3],
    ],
    steps: [
      "Cortá las papas en rodajas finas y la cebolla en pluma. Mezclalas con el aceite y sal.",
      "Horneá en una fuente a 200 °C, 20 minutos, hasta que estén tiernas.",
      "Mientras, blanqueá la espinaca 1 minuto en agua hirviendo, escurrila bien y picala.",
      "Batí los huevos con sal, sumá la espinaca y las papas con la cebolla.",
      "Volcá en una fuente aceitada y horneá 15-20 minutos a 180 °C hasta que cuaje.",
    ],
    storage: "3 días en heladera.",
  },
  {
    slug: "guiso-lentejas-light",
    name: "Guiso de lentejas light",
    emoji: "🍲",
    description: "Guiso bien argentino con más verdura y carne magra.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["meal prep", "freezer", "alto en fibra", "alto en proteína"],
    servings: 6,
    prep: 20,
    cook: 50,
    difficulty: "media",
    ingredients: [
      ["lentejas", 300, "remojadas"],
      ["nalga", 300, "en cubos"],
      ["cebolla", 150],
      ["morron-rojo", 150],
      ["zanahoria", 150],
      ["zapallo", 300],
      ["tomate-triturado", 520],
      ["pimenton", 4],
      ["comino", 2],
      ["laurel", 0.4, "2 hojas"],
      ["aceite-girasol", 10],
      ["sal", 4],
    ],
    steps: [
      "Remojá las lentejas desde la noche anterior (o al menos 2 horas) y escurrilas.",
      "En una olla con el aceite, sellá la carne en cubos. Retirala.",
      "Rehogá la cebolla, el morrón y la zanahoria picados 5 minutos.",
      "Volvé a poner la carne, sumá pimentón, comino, laurel, el tomate y 1 litro de agua caliente.",
      "Agregá las lentejas y la calabaza en cubos. Cociná tapado a fuego bajo 35-40 minutos, revolviendo cada tanto.",
      "Ajustá la sal y dejá reposar 5 minutos antes de servir. Rinde 6 platos.",
    ],
    storage: "4 días en heladera, 3 meses en freezer.",
  },
  {
    slug: "ensalada-completa-atun",
    name: "Ensalada completa de atún",
    emoji: "🥗",
    description: "Almuerzo frío, completo y súper práctico para llevar.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "rápido", "sin gluten"],
    servings: 1,
    prep: 10,
    cook: 15,
    ingredients: [
      ["atun-lata", 120, "1 lata escurrida"],
      ["huevo", 50],
      ["papa", 150],
      ["chaucha", 100],
      ["tomate", 120],
      ["lechuga", 60],
      ["aceite-oliva", 5],
      ["limon", 15],
      ["sal", 0.5],
    ],
    steps: [
      "Hervé la papa en cubos (12 min), las chauchas (6 min) y el huevo (9 min). Enfriá todo.",
      "Cortá el tomate y la lechuga.",
      "Armá el plato con todas las verduras, el atún escurrido y el huevo en cuartos.",
      "Condimentá con el aceite, limón y sal.",
    ],
    tips: "Ideal para cocinar papa, chauchas y huevos para 3 días de una vez.",
  },
  {
    slug: "hamburguesas-caseras-ensalada",
    name: "Hamburguesas caseras al plato con ensalada",
    emoji: "🍔",
    description: "Hamburguesas de carne magra hechas en casa. Rinden 4.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "freezer", "sin gluten"],
    servings: 4,
    prep: 15,
    cook: 12,
    ingredients: [
      ["carne-picada-magra", 500],
      ["cebolla", 100],
      ["huevo", 50],
      ["ajo", 5],
      ["perejil", 8],
      ["lechuga", 200],
      ["tomate", 300],
      ["sal", 2],
    ],
    steps: [
      "Picá la cebolla, el ajo y el perejil bien finito.",
      "Mezclá con la carne, el huevo y la sal. Formá 4 hamburguesas de igual tamaño.",
      "Cocinalas en plancha o sartén bien caliente 4-5 minutos por lado.",
      "Serví cada una con lechuga y tomate. Si querés pan, sumá un pan integral (+150 kcal).",
    ],
    storage: "Crudas se freezan separadas con nylon hasta 3 meses.",
  },
  {
    slug: "pastel-papa-light",
    name: "Pastel de papa light",
    emoji: "🥘",
    description: "Con puré mixto de papa y calabaza y relleno bien condimentado.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["meal prep", "freezer", "alto en proteína"],
    servings: 5,
    prep: 25,
    cook: 40,
    difficulty: "media",
    ingredients: [
      ["carne-picada-magra", 500],
      ["cebolla", 200],
      ["morron-rojo", 150],
      ["huevo", 50, "duro"],
      ["papa", 600],
      ["zapallo", 400],
      ["leche-descremada", 100],
      ["queso-rallado", 20],
      ["pimenton", 3],
      ["comino", 1],
      ["sal", 4],
    ],
    steps: [
      "Hervé la papa y la calabaza en cubos hasta que estén tiernas; hacé un puré con la leche y sal.",
      "Rehogá la cebolla y el morrón picados con un chorrito de agua hasta que estén blandos.",
      "Sumá la carne y cociná desgranándola hasta que pierda el color rosado. Condimentá con pimentón, comino y sal.",
      "Poné el relleno en una fuente, distribuí el huevo duro picado y cubrí con el puré.",
      "Espolvoreá con queso rallado y gratiná a 200 °C unos 15-20 minutos.",
      "Cortá en 5 porciones.",
    ],
    storage: "4 días en heladera; se freeza en porciones.",
  },
  {
    slug: "cazuela-pollo-verduras",
    name: "Cazuela de pollo con verduras",
    emoji: "🍛",
    description: "Guisito de pollo rendidor, ideal para el invierno.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["meal prep", "freezer", "alto en proteína", "sin gluten"],
    servings: 4,
    prep: 20,
    cook: 35,
    ingredients: [
      ["pechuga-pollo", 600, "en cubos"],
      ["cebolla", 150],
      ["morron-rojo", 150],
      ["zanahoria", 150],
      ["papa", 300],
      ["choclo-lata", 150],
      ["tomate-triturado", 260],
      ["pimenton", 3],
      ["laurel", 0.2],
      ["aceite-girasol", 10],
      ["sal", 3],
    ],
    steps: [
      "Dorá el pollo en cubos con el aceite en una olla. Retiralo.",
      "Rehogá cebolla, morrón y zanahoria en cubos 5 minutos.",
      "Volvé a poner el pollo, sumá pimentón, laurel, tomate y 500 ml de agua caliente.",
      "Agregá las papas en cubos y cociná tapado 20 minutos a fuego bajo.",
      "Al final sumá el choclo, ajustá la sal y cociná 5 minutos más.",
    ],
    storage: "4 días en heladera, 3 meses en freezer.",
  },
  {
    slug: "fideos-bolognesa-light",
    name: "Fideos integrales con bolognesa light",
    emoji: "🍝",
    description: "Pasta medida (80 g por plato) con salsa de carne magra y verduras escondidas.",
    mealTypes: ["almuerzo"],
    tags: ["post-entreno", "alto en proteína"],
    servings: 4,
    prep: 15,
    cook: 30,
    ingredients: [
      ["fideos-integrales", 320],
      ["carne-picada-magra", 300],
      ["tomate-triturado", 520],
      ["cebolla", 150],
      ["zanahoria", 100, "rallada"],
      ["ajo", 5],
      ["oregano", 1],
      ["aceite-oliva", 5],
      ["queso-rallado", 20],
      ["sal", 3],
    ],
    steps: [
      "Rehogá la cebolla, el ajo y la zanahoria rallada con el aceite 5 minutos.",
      "Sumá la carne y cociná desgranando hasta que se dore.",
      "Agregá el tomate, orégano, sal y medio vaso de agua. Cociná a fuego bajo 20 minutos.",
      "Hervé los fideos en abundante agua con sal según el paquete y escurrí.",
      "Serví 1/4 de los fideos con 1/4 de la salsa y 5 g de queso rallado por plato.",
    ],
    tips: "Pesá los fideos crudos: 80 g por persona es una porción generosa.",
    storage: "La salsa dura 4 días en heladera y se freeza.",
  },
  {
    slug: "revuelto-zapallitos",
    name: "Revuelto de zapallitos",
    emoji: "🥒",
    description: "Cena express, liviana y con proteína.",
    mealTypes: ["cena"],
    tags: ["rápido", "vegetariano", "bajo en carbohidratos", "sin gluten"],
    servings: 2,
    prep: 10,
    cook: 15,
    ingredients: [
      ["zapallito", 400],
      ["cebolla", 100],
      ["huevo", 150, "3 unidades"],
      ["aceite-oliva", 5],
      ["sal", 1.5],
    ],
    steps: [
      "Cortá la cebolla en pluma y los zapallitos en cubos o bastones.",
      "Saltá la cebolla con el aceite 3 minutos, sumá los zapallitos y cociná 8-10 minutos hasta que estén tiernos.",
      "Agregá los huevos batidos con sal y revolvé a fuego bajo hasta que cuajen.",
    ],
  },
  {
    slug: "pizza-integral-casera",
    name: "Pizza integral casera",
    emoji: "🍕",
    description: "Para el finde sin culpa: masa integral y porción medida (2 porciones por plato).",
    mealTypes: ["cena"],
    tags: ["vegetariano", "finde"],
    servings: 4,
    prep: 20,
    cook: 25,
    difficulty: "media",
    ingredients: [
      ["harina-integral", 250],
      ["levadura", 7],
      ["aceite-oliva", 10],
      ["sal", 3],
      ["tomate-triturado", 200],
      ["mozzarella", 200],
      ["tomate", 150, "en rodajas"],
      ["oregano", 1],
    ],
    steps: [
      "Mezclá la harina con la levadura, la sal, el aceite y ~160 ml de agua tibia hasta formar una masa.",
      "Amasá 8 minutos y dejá levar tapada 40 minutos (o hasta que duplique).",
      "Estirala en una pizzera aceitada y precocinala 8 minutos a 220 °C.",
      "Cubrí con el tomate triturado condimentado, la mozzarella, rodajas de tomate y orégano.",
      "Horneá 12-15 minutos más hasta que el queso se gratine. Cortá en 8 porciones (2 por persona).",
    ],
  },
  {
    slug: "wraps-pollo-vegetales",
    name: "Wraps de pollo y vegetales",
    emoji: "🌮",
    description: "Dos wraps por plato, con pollo salteado y verduras frescas.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "rápido"],
    servings: 2,
    prep: 15,
    cook: 10,
    ingredients: [
      ["tortilla-integral", 160, "4 unidades"],
      ["pechuga-pollo", 300, "en tiras"],
      ["morron-rojo", 100],
      ["cebolla", 100],
      ["lechuga", 100],
      ["tomate", 150],
      ["queso-untable-light", 60],
      ["aceite-oliva", 5],
      ["pimenton", 2],
      ["sal", 1],
    ],
    steps: [
      "Saltá el pollo en tiras con el aceite, pimentón y sal 6-7 minutos.",
      "Sumá la cebolla y el morrón en tiras y cociná 3 minutos más.",
      "Calentá las tortillas y untalas con el queso.",
      "Rellená con el salteado, lechuga y tomate. Enrollá. 2 wraps por persona.",
    ],
  },
  {
    slug: "berenjenas-rellenas",
    name: "Berenjenas rellenas de carne",
    emoji: "🍆",
    description: "Cada porción es media berenjena. Acompañá con ensalada.",
    mealTypes: ["cena", "almuerzo"],
    tags: ["bajo en carbohidratos", "sin gluten", "alto en proteína"],
    servings: 4,
    prep: 20,
    cook: 35,
    difficulty: "media",
    ingredients: [
      ["berenjena", 600, "2 unidades"],
      ["carne-picada-magra", 250],
      ["cebolla", 100],
      ["morron-rojo", 100],
      ["tomate-triturado", 200],
      ["queso-cremoso-light", 60],
      ["aceite-oliva", 5],
      ["sal", 2],
    ],
    steps: [
      "Cortá las berenjenas al medio a lo largo, hacé cortes en cuadrícula en la pulpa y horneá 20 minutos a 200 °C.",
      "Retirá la pulpa con una cuchara dejando 1 cm de borde y picala.",
      "Rehogá cebolla y morrón con el aceite, sumá la carne y cociná. Agregá la pulpa y el tomate; cociná 5 minutos.",
      "Rellená las berenjenas, cubrí con el queso en láminas y gratiná 10 minutos.",
    ],
    storage: "3 días en heladera.",
  },
  {
    slug: "ensalada-garbanzos",
    name: "Ensalada de garbanzos, tomate y pepino",
    emoji: "🫘",
    description: "Opción vegetariana fresca con proteína de legumbres y huevo.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["vegetariano", "alto en fibra", "rápido", "sin gluten"],
    servings: 2,
    prep: 15,
    cook: 10,
    ingredients: [
      ["garbanzos-lata", 240, "1 lata enjuagada"],
      ["tomate", 200],
      ["pepino", 200],
      ["cebolla-morada", 50],
      ["perejil", 10],
      ["huevo", 100, "2 duros"],
      ["aceite-oliva", 10],
      ["limon", 20],
      ["sal", 1],
    ],
    steps: [
      "Enjuagá y escurrí los garbanzos.",
      "Cortá el tomate y el pepino en cubos, la cebolla en pluma finita y picá el perejil.",
      "Hervé los huevos 9 minutos y cortalos en cuartos.",
      "Mezclá todo con el aceite, limón y sal. Dividí en 2 platos.",
    ],
    storage: "2 días en heladera (sin condimentar es mejor).",
  },
  {
    slug: "sopa-crema-calabaza",
    name: "Sopa crema de calabaza",
    emoji: "🎃",
    description: "Entrada de muy pocas calorías que llena mucho. Sumale una proteína.",
    mealTypes: ["cena", "almuerzo"],
    tags: ["vegetariano", "freezer", "sin gluten", "bajo en grasa"],
    servings: 4,
    prep: 10,
    cook: 25,
    ingredients: [
      ["zapallo", 800],
      ["cebolla", 150],
      ["zanahoria", 100],
      ["leche-descremada", 200],
      ["aceite-oliva", 5],
      ["nuez-moscada", 0.3],
      ["sal", 3],
    ],
    steps: [
      "Rehogá la cebolla con el aceite 3 minutos.",
      "Sumá la calabaza y la zanahoria en cubos y cubrí apenas con agua.",
      "Cociná 20 minutos hasta que estén muy tiernas.",
      "Procesá con mixer, agregá la leche, sal y nuez moscada. Calentá sin que hierva.",
    ],
    tips: "Combinala con un omelette o una pechuga a la plancha para una cena completa.",
    storage: "4 días en heladera; se freeza muy bien.",
  },
  {
    slug: "pollo-mostaza-brocoli-arroz",
    name: "Pollo a la mostaza con brócoli y arroz integral",
    emoji: "🍚",
    description: "Salsa cremosa sin crema: queso untable descremado y mostaza.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "meal prep"],
    servings: 4,
    prep: 10,
    cook: 35,
    ingredients: [
      ["pechuga-pollo", 500],
      ["mostaza", 30],
      ["queso-untable-light", 60],
      ["cebolla", 100],
      ["brocoli", 400],
      ["arroz-integral", 120],
      ["aceite-oliva", 5],
      ["sal", 2],
    ],
    steps: [
      "Cociná el arroz integral en agua con sal 30-35 minutos.",
      "Dorá el pollo en cubos con el aceite; sumá la cebolla picada y cociná 3 minutos.",
      "Agregá la mostaza, el queso untable y 100 ml de agua; cociná 5 minutos hasta que espese.",
      "Hervé o cociná al vapor el brócoli 4-5 minutos (que quede verde y firme).",
      "Serví 1/4 de arroz, 1/4 de pollo con salsa y brócoli.",
    ],
    storage: "4 días en heladera.",
  },
  {
    slug: "bowl-arroz-pollo-palta",
    name: "Bowl de arroz, pollo y palta",
    emoji: "🍱",
    description: "Estilo poke: completo, colorido y fácil de armar.",
    mealTypes: ["almuerzo"],
    tags: ["alto en proteína", "post-entreno"],
    servings: 1,
    prep: 10,
    cook: 15,
    ingredients: [
      ["arroz-blanco", 60],
      ["pechuga-pollo", 120],
      ["palta", 50],
      ["pepino", 60],
      ["zanahoria", 50, "rallada"],
      ["salsa-soja", 10],
      ["sesamo", 3],
    ],
    steps: [
      "Cociná el arroz y dejalo entibiar.",
      "Cociná la pechuga a la plancha y cortala en tiras.",
      "Armá el bowl: arroz de base y arriba pollo, palta en láminas, pepino y zanahoria.",
      "Terminá con la salsa de soja y el sésamo.",
    ],
  },
  {
    slug: "carre-cerdo-pure-batata",
    name: "Carré de cerdo con puré de batata y manzana",
    emoji: "🐖",
    description: "El cerdo magro es una gran opción: el carré tiene poca grasa.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "sin gluten"],
    servings: 4,
    prep: 15,
    cook: 30,
    ingredients: [
      ["carre-cerdo", 600],
      ["batata", 600],
      ["manzana", 180],
      ["mostaza", 20],
      ["aceite-oliva", 10],
      ["sal", 3],
    ],
    steps: [
      "Untá las bifes de carré con mostaza y sal.",
      "Hervé la batata y la manzana en cubos 15 minutos; escurrí y hacé puré.",
      "Cociná el carré en sartén con el aceite 4-5 minutos por lado (que quede apenas rosado adentro).",
      "Serví cada porción con puré.",
    ],
  },
  {
    slug: "ensalada-cesar-light",
    name: "Ensalada César light con pollo",
    emoji: "🥬",
    description: "Aderezo de yogur y mostaza en lugar de mayonesa.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "rápido"],
    servings: 1,
    prep: 10,
    cook: 10,
    ingredients: [
      ["lechuga", 200],
      ["pechuga-pollo", 150],
      ["pan-integral", 25, "en cubitos tostados"],
      ["queso-rallado", 10],
      ["yogur-descremado", 40],
      ["mostaza", 5],
      ["limon", 10],
      ["ajo", 2],
      ["sal", 0.5],
    ],
    steps: [
      "Cociná el pollo a la plancha y cortalo en tiras.",
      "Tostá el pan en cubitos en sartén o en el horno.",
      "Mezclá el yogur con mostaza, limón, ajo rallado y sal para el aderezo.",
      "Armá la ensalada con la lechuga, el pollo, los crutones y el queso; bañá con el aderezo.",
    ],
  },
  {
    slug: "hamburguesas-lentejas",
    name: "Hamburguesas de lentejas",
    emoji: "🌱",
    description: "Medallones veggie con mucha fibra. 2 por porción.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["vegetariano", "freezer", "alto en fibra"],
    servings: 3,
    prep: 20,
    cook: 40,
    difficulty: "media",
    ingredients: [
      ["lentejas", 200],
      ["cebolla", 100],
      ["zanahoria", 100],
      ["avena", 50],
      ["huevo", 50],
      ["comino", 2],
      ["aceite-girasol", 10],
      ["sal", 2],
    ],
    steps: [
      "Hervé las lentejas 20-25 minutos hasta que estén bien tiernas y escurrilas muy bien.",
      "Rehogá la cebolla picada y la zanahoria rallada.",
      "Pisá las lentejas y mezclá con las verduras, el huevo, la avena, el comino y la sal.",
      "Formá 6 medallones y llevá 20 minutos a la heladera para que tomen firmeza.",
      "Cocinalos en sartén pincelada con aceite o al horno a 200 °C 10 minutos por lado.",
    ],
    tips: "Acompañalas con ensalada de tomate y una cucharada de yogur con limón.",
    storage: "Crudas se freezan hasta 3 meses.",
  },
  {
    slug: "arroz-con-pollo-light",
    name: "Arroz con pollo light",
    emoji: "🥘",
    description: "Clásico de la abuela con menos aceite y más verdura.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["meal prep", "post-entreno", "sin gluten"],
    servings: 4,
    prep: 15,
    cook: 30,
    ingredients: [
      ["arroz-blanco", 200],
      ["pechuga-pollo", 400],
      ["cebolla", 150],
      ["morron-rojo", 150],
      ["arvejas-lata", 150],
      ["tomate-triturado", 200],
      ["curcuma", 2],
      ["aceite-girasol", 10],
      ["sal", 3],
    ],
    steps: [
      "Dorá el pollo en cubos con el aceite y retiralo.",
      "Rehogá cebolla y morrón picados 5 minutos.",
      "Sumá el arroz y nacaralo 1 minuto. Agregá cúrcuma, tomate, el pollo y 600 ml de agua caliente con sal.",
      "Cociná tapado a fuego bajo 15-18 minutos sin revolver.",
      "Sumá las arvejas, apagá y dejá reposar 5 minutos tapado.",
    ],
    storage: "3 días en heladera.",
  },
  {
    slug: "pechuga-plancha-ensalada-mixta",
    name: "Pechuga a la plancha con ensalada mixta",
    emoji: "🍽️",
    description: "La cena más simple y efectiva del déficit.",
    mealTypes: ["cena", "almuerzo"],
    tags: ["alto en proteína", "rápido", "bajo en carbohidratos", "sin gluten"],
    servings: 1,
    prep: 5,
    cook: 12,
    ingredients: [
      ["pechuga-pollo", 180],
      ["lechuga", 100],
      ["tomate", 150],
      ["zanahoria", 60, "rallada"],
      ["aceite-oliva", 7],
      ["limon", 10],
      ["sal", 1],
    ],
    steps: [
      "Aplaná un poco la pechuga para que se cocine pareja. Salpimentá.",
      "Cociná en plancha bien caliente 5-6 minutos por lado.",
      "Armá la ensalada y condimentá con el aceite, limón y sal.",
    ],
  },
  {
    slug: "peceto-horno-verduras",
    name: "Peceto al horno con verduras asadas",
    emoji: "🥕",
    description: "Corte magrísimo; ideal para hacer de a mucho y usar en la semana.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "meal prep", "sin gluten"],
    servings: 4,
    prep: 15,
    cook: 50,
    ingredients: [
      ["peceto", 700],
      ["zanahoria", 300],
      ["cebolla", 200],
      ["morron-rojo", 200],
      ["zapallito", 300],
      ["aceite-oliva", 15],
      ["ajo", 10],
      ["oregano", 2],
      ["sal", 4],
    ],
    steps: [
      "Precalentá el horno a 200 °C. Frotá el peceto con ajo picado, orégano, sal y un poco de aceite.",
      "Cortá las verduras en trozos grandes, mezclalas con el resto del aceite y sal.",
      "Poné el peceto en el centro de la asadera con las verduras alrededor.",
      "Horneá 45-50 minutos (punto jugoso) dándolo vuelta a mitad de cocción.",
      "Dejá reposar 10 minutos antes de cortar en rodajas finas.",
    ],
    tips: "Las sobras frías en rodajas finas son perfectas para sándwiches o ensaladas.",
    storage: "4 días en heladera.",
  },
  {
    slug: "zapallitos-rellenos-atun",
    name: "Zapallitos rellenos de atún",
    emoji: "🥒",
    description: "Cena liviana y económica.",
    mealTypes: ["cena"],
    tags: ["bajo en carbohidratos", "alto en proteína"],
    servings: 2,
    prep: 15,
    cook: 25,
    ingredients: [
      ["zapallito", 600, "3 redondos"],
      ["atun-lata", 120],
      ["cebolla", 80],
      ["huevo", 50],
      ["queso-rallado", 15],
      ["pan-rallado", 10],
      ["sal", 1],
    ],
    steps: [
      "Hervé los zapallitos enteros 8 minutos, cortalos al medio y retirá la pulpa.",
      "Rehogá la cebolla, sumá la pulpa picada y cociná 3 minutos.",
      "Fuera del fuego mezclá con el atún, el huevo y sal.",
      "Rellená los zapallitos, espolvoreá con queso y pan rallado y gratiná 15 minutos a 200 °C.",
    ],
  },
  {
    slug: "salteado-carne-chauchas",
    name: "Salteado de carne con chauchas y papa",
    emoji: "🍳",
    description: "Plato único rápido de sartén.",
    mealTypes: ["almuerzo", "cena"],
    tags: ["alto en proteína", "sin gluten"],
    servings: 2,
    prep: 10,
    cook: 20,
    ingredients: [
      ["bola-lomo", 300, "en tiras"],
      ["chaucha", 250],
      ["papa", 250],
      ["cebolla", 100],
      ["aceite-girasol", 8],
      ["pimenton", 2],
      ["sal", 2],
    ],
    steps: [
      "Hervé la papa en cubos 8 minutos y las chauchas 5 minutos. Escurrí.",
      "Saltá la carne en tiras en sartén bien caliente con el aceite 3-4 minutos. Retirala.",
      "En la misma sartén dorá la cebolla, la papa y las chauchas 5 minutos.",
      "Volvé a sumar la carne, condimentá con pimentón y sal, y serví.",
    ],
  },

  /* ============================ SNACKS / COLACIONES ============================ */
  {
    slug: "hummus-bastones-zanahoria",
    name: "Hummus con bastones de zanahoria",
    emoji: "🥕",
    description: "Colación crocante y saciante.",
    mealTypes: ["snack", "merienda"],
    tags: ["vegetariano", "meal prep", "sin gluten"],
    servings: 4,
    prep: 10,
    cook: 0,
    ingredients: [
      ["garbanzos-lata", 240],
      ["limon", 30],
      ["ajo", 3],
      ["aceite-oliva", 10],
      ["comino", 1],
      ["sal", 1],
      ["zanahoria", 300, "en bastones"],
    ],
    steps: [
      "Procesá los garbanzos con el limón, el ajo, el aceite, el comino, la sal y 3-4 cucharadas de agua fría.",
      "Ajustá la textura con más agua si hace falta.",
      "Cortá las zanahorias en bastones y serví con 1/4 del hummus por porción.",
    ],
    storage: "El hummus dura 4 días en heladera.",
  },
  {
    slug: "manzana-pasta-mani",
    name: "Manzana con pasta de maní",
    emoji: "🍏",
    description: "Dulce, crocante y con grasas buenas.",
    mealTypes: ["snack", "merienda"],
    tags: ["rápido", "sin cocción", "vegetariano"],
    servings: 1,
    prep: 2,
    cook: 0,
    ingredients: [
      ["manzana", 180],
      ["pasta-mani", 15],
    ],
    steps: ["Cortá la manzana en gajos.", "Serví con una cucharada de pasta de maní para untar."],
  },
  {
    slug: "galletas-arroz-queso-tomate",
    name: "Galletas de arroz con queso untable y tomate",
    emoji: "🍘",
    description: "Colación salada de menos de 120 kcal.",
    mealTypes: ["snack", "merienda"],
    tags: ["rápido", "sin cocción", "vegetariano"],
    servings: 1,
    prep: 3,
    cook: 0,
    ingredients: [
      ["galletas-arroz", 18, "2 unidades"],
      ["queso-untable-light", 30],
      ["tomate", 50],
      ["oregano", 0.2],
    ],
    steps: ["Untá las galletas con el queso.", "Cubrí con rodajas finas de tomate y orégano."],
  },
  {
    slug: "helado-banana",
    name: "Helado de banana y cacao (nice cream)",
    emoji: "🍨",
    description: "Postre cremoso sin azúcar agregada.",
    mealTypes: ["snack", "merienda"],
    tags: ["sin azúcar", "vegetariano", "postre"],
    servings: 1,
    prep: 5,
    cook: 0,
    ingredients: [
      ["banana", 120, "congelada en rodajas"],
      ["cacao", 5],
      ["leche-descremada", 30],
    ],
    steps: [
      "Cortá la banana en rodajas y congelala al menos 4 horas.",
      "Procesá la banana congelada con el cacao y la leche hasta que quede cremosa.",
      "Comelo al momento (o freezá 20 minutos para que quede más firme).",
    ],
  },
  {
    slug: "mix-frutos-secos",
    name: "Porción de frutos secos",
    emoji: "🥜",
    description: "Porción controlada de almendras y nueces.",
    mealTypes: ["snack"],
    tags: ["sin cocción", "rápido"],
    servings: 1,
    prep: 1,
    cook: 0,
    ingredients: [
      ["almendras", 15],
      ["nueces", 10],
    ],
    steps: ["Pesá la porción (25 g) y guardala en un frasquito para no picar de más."],
  },
  {
    slug: "yogur-griego-frutas",
    name: "Yogur griego con fruta",
    emoji: "🍑",
    description: "Colación alta en proteína.",
    mealTypes: ["snack", "merienda"],
    tags: ["alto en proteína", "rápido", "sin cocción"],
    servings: 1,
    prep: 2,
    cook: 0,
    ingredients: [
      ["yogur-griego", 160],
      ["durazno", 100],
    ],
    steps: ["Cortá la fruta en cubos y mezclala con el yogur."],
  },
];
